spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 200MB
      max-request-size: 215MB


file:
  downloadPath: C:/Users/Admin/Downloads/
  uploadPath: C:/Users/Admin/Pictures/Screenshots/

